config/routes.rb
Mvp::Application.routes.draw do
  root 'pages#index'

  post 'contact', to: 'contact#create', as: 'contact_create'

  controller :pages do
    get 'faq', to: 'pages#faq'
    get 'location', to: 'pages#location'
    get 'contact-us', to: 'pages#contact', as: 'contact'
    get 'about-us', to: 'pages#about', as: 'about'
  end

  get '/inventory', to: 'cars#inventory'
  resources :cars

  resources :uploads

  match '/dashboard', to: 'users#dashboard', via: 'get'
  resources :users

  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  resources :sessions, only: [:new, :create, :destroy]

  resources :reviews
end

app/views/pages/_general_info.html.haml
%section#general-info
  .row
    .small-12.medium-4.columns
      = image_tag 'https://s3-us-west-2.amazonaws.com/mvp-used-cars/images/home/general-info/clock.svg', onerror: "this.onerror=null; this.src='https://s3-us-west-2.amazonaws.com/mvp-used-cars/images/home/general-info/clock.png'"
      %p
        0900-1730
        %br
        Monday-Saturday
        %br
        Appointments available
    .smal-12.medium-4.columns
      = image_tag 'https://s3-us-west-2.amazonaws.com/mvp-used-cars/images/home/general-info/phone.svg', onerror: "this.onerror=null; this.src='https://s3-us-west-2.amazonaws.com/mvp-used-cars/images/home/general-info/phone.png'"
      %p
        %a{ href: 'tel:080-4058-5771' } 080-4058-5771
        %br
        %a{ href: 'tel:0176-58-6903' } 0176-58-6903
        %br
        %a{ href: 'mailto:sales@mvpusedcars.com' } Sales@MVPUsedCars.com
    .small-12.medium-4.columns
      = image_tag 'https://s3-us-west-2.amazonaws.com/mvp-used-cars/images/home/general-info/location.svg', onerror: "this.onerror=null; this.src='https://s3-us-west-2.amazonaws.com/mvp-used-cars/images/home/general-info/location.png'"
      %p
        Exit the POL/Falcon Gate. Continue straight until the first stop light.
        MVP Used Cars will be on right

app/views/pages/about.html.haml
= content_for :title do
  About Us - Misawa Used Cars
%div#hero
  %header
    .row
      .small-6.small-centered.columns
        = image_tag 'about/header/about.svg', onerror: "this.onerror=null; this.src='/assets/about/header/about.png'"
      %h1
        About Us
      %p
        Learn about our company and what makes us the best place to purchase a car in Misawa Air Force Base
%section.row
  %p
    %span
      MVP Used Cars
    is an used car dealership company. We are based in Misawa Air Force Base, Japan. We have been serving the men and women of Misawa Air Force Base with quality used cars for over 10 years
  %ul.circle
    %li
      %p
        %span
          Competitive pricing
        We are committed to give you the best price and value for car purchase. Talk to us and we can find a way to fit your budget.
    %li
      %p
        %span
          Service
        Our staff members are Air Force retirees, so we understand what you will need to find the perfect car for your staff here in Misawa.
    %li
      %p
        %span
          Quality
        Our cars are reliable and ready to be purchased today. Our cars would last you your whole stay in Misawa and years afterwards.
  %p
    To get started simply
    = link_to 'Contact Us', contact_path
    , and tell us about your vehicle needs

app/views/pages/contact.html.haml
= content_for :title do
  Contact Us - Misawa Used Cars
%div#hero
  %header
    .row
      .small-6.small-centered.columns
        = image_tag 'https://s3-us-west-2.amazonaws.com/mvp-used-cars/images/contact/header/contact.svg', onerror: "this.onerror=null; this.src='https://s3-us-west-2.amazonaws.com/mvp-used-cars/images/contact/header/contact.png'"
      %h1
        Contact Us
      %p
        There are many ways to get in touch. Drop by the shop, give us a call, or send us an email.
= render 'general_info'
#send-us-a-message
  .row
    .small-12.small-centered.columns
      %h2
        Send us a message
%section#email-form
  .row
    .small-12.columns
    = form_for @message, url: contact_create_path, html: {  class: 'large-12 columns', data: { abide: true } } do |f|
      .row
        .sweet-honey
          = f.label :sweet_honey, "This is a honeypot, if you see this you're CSS is turned off or you're a bot. If you're not a bot don't fill it in."
          = f.text_field :sweet_honey
        .small-12.columns
          = f.label :name
          %span.user-icon
          = f.text_field( :name, placeholder: 'Name*', 'required pattern' => '[a-zA-Z]' )
          %small.error
            Name is required
        .small-12.columns
          = f.label :email
          %span.email-icon
          = f.email_field( :email, placeholder: 'Email Address*', pattern: 'email', required: true )
          %small.error
            Please enter a valid email
        .small-12.columns
          = f.label :phone
          %span.phone-icon
          = f.telephone_field( :phone, placeholder: 'Phone number' )
        .small-12.columns
          = f.label :subject
          %span.subject-icon
          = f.text_field( :subject, placeholder: 'Subject', value: @subject )
        #form-message.small-12.columns
          = f.label :body
          %span.message-icon
          = f.text_area( :body, placeholder: 'Message' )
          %small.error
            Message is required
        .small-12.columns
          = f.submit( 'Send', class: 'button small small-12 columns' )
#connect-with-us
  .div
    .row
      .small-12.small-centered.columns
        %h3
          %span
            or
          %br
          Connect with Us
  .row
    #social-links.small-12.medium-4.medium-centered.columns
      %ul.inline-list
        %li
          %a.facebook{ href: 'https://facebook.com/mvpusedcars' }
        %li
          %a.twitter{ href: 'https://twitter.com/mvpusedcars' }
        %li
          %a.gplus{ href: 'https://plus.google.com/114770703043987053078/about' }
        %li
          %a.pinterest{ href: 'http://www.pinterest.com/mvpusedcars/' }

app/views/pages/faq.html.haml
= content_for :title do
  Frequently Asked Questions - Used cars in Misawa
%div#hero
  %header
    .row
      .small-6.small-centered.columns
        = image_tag 'https://s3-us-west-2.amazonaws.com/mvp-used-cars/images/faq/header/faq.svg', onerror: "this.onerror=null; this.src='https://s3-us-west-2.amazonaws.com/mvp-used-cars/images/faq/header/faq.png'"
      %h1
        Frequently Asked Questions
      %p
        These FAQs answer everything you'll need to know to buy a car in Misawa
%section
  .row
    %dl.accordion( data-accordion )
      %dd
        %a.active{ href: '#panel1' }
          Why should I purchase a car from MVP Used Cars?
        #panel1.content.active
          When you purchase from MVP Used Cars, you get a quality vehicle with 2 years of JCI, 30 day bumper to bumper, and 6 month engine and transmission.
          Our staff includes retired military that are familiar with the whole process of purchasing and owning a car in Misawa. You’re in good hands
      %dd
        %a{ href: '#panel2' }
          What is JCI?
        #panel2.content
          JCI stands for Japanese Compulsory Insurance. Japan requires that all cars must have this minimum amount of insurance. All car purchases from comes with 2 year JCI.
      %dd
        %a{ href: '#panel3' }
          Is JCI considered Liability Insurance?
        #panel3.content
          JCI is different from Liability insurance. Liability can be purchased at AIU or Ford Insurance Company off-base. It can be purchased 3 month, 6 and up to 1 year
      %dd
        %a{ href: '#panel4' }
          Is JCI considered Liability Insurance?
        #panel4.content
          JCI is different from Liability insurance. Liability can be purchased at AIU or Ford Insurance Company off-base. It can be purchased 3 month, 6 and up to 1 year
      %dd
        %a{ href: '#panel5' }
          What is Road Tax?
        #panel5.content
          Road Tax is paid once a year every April. The amount depends on the size/type of vehicle and can vary from 10,000 - 18,000 yen
      %dd
        %a{ href: '#panel6' }
          Can I buy cars without JCI?
        #panel6.content
          Yes, you can either do the JCI yourself or ask an off-base company to do the JCI for you.
      %dd
        %a{ href: '#panel7' }
          Can I buy a car as-is from MVP Used Cars?
        #panel7.content
          Yes, you can buy a car as-is, without JCI. If you do choose to purchase a car as-is, then MVP Used Cars guarantees the car passes inspection.
      %dd
        %a{ href: '#panel8' }
          Why would I want to buy a car as-is?
        #panel8.content
          You can save some money by not including our 6 months engine/transmission warranty. If you do choose to purchase a car as-is, then MVP Used Cars guarantees the car passes inspection.
      %dd
        %a{ href: '#panel9' }
          Do you give a loaner car if my car needs repairs?
        #panel9.content
          Yes, if your car needs to get repaired for more than 1 day, then we will give you a rental car.
      %dd
        %a{ href: '#panel10' }
          After 2 years, can you re-JCI my car?
        #panel10.content
          Yes, we are more than happy to take care of your JCI when your JCI expires.
      %dd
        %a{ href: '#panel11' }
          Can I purchase a car before I arrive to Misawa?
        #panel11.content
          Yes, you can view our current inventory online, and we can negotiate the price. After you have decided, we can have your car ready for you to pick up once you arrive. Additionally, we will give you a free extended warranty if you purchase online.
      %dd
        %a{ href: '#panel12' }
          I want to buy a car in cash, so can I get a discount?
        #panel12.content
          Yes, we offer discounts on our cars if purchased in cash. Just make an offer.
      %dd
        %a{ href: '#panel13' }
          Do you offer financing?
        #panel13.content
          Yes, we have in house financing with affordable monthly interest free payments.
      %dd
        %a{ href: '#panel14' }
          Are all your cars good at snow?
        #panel14.content
          Yes, most of our cars are 4WD.
      %dd
        %a{ href: '#panel15' }
          Does your car come with 2 sets of tires?
        #panel15.content
          If the car comes with summer tires, then we’ll include a set of Mud and Snow tires, also known as all year round tires, for free. If the car already has mud and snow tires, then you have the option of another set of summer or all season tires.
      %dd
        %a{ href: '#panel16' }
          Do you offer incentives?
        #panel16.content
          Yes, we have a variety of incentives to offer you upon negotiation.

app/views/pages/index.html.haml
= content_for :title do
  Misawa Used Cars - Misawa Auto Sales
%div#hero
  %header
    .row
      %h1
        Quality Cars for our U.S. Armed Forces
      %p
        Serving Misawa AFB's men and women for more then ten years.
      = link_to inventory_path do
        .button View Our Inventory
= render 'general_info'
%section#our-customers
  %h2.section-title
    Meet Our Customers
  .customers-row
  %ul.slides.hide-for-medium-down{ 'data-options' => 'resume_on_mouseout:true', data: {orbit: true} }
    %li
      - @reviews[0...3].each do |review|
        .customer-review
          .quote-meta
            .quote
              .inner
                %p
                  = truncate_review review
            .quotee
              .inner
                %p{ class: 'name' }
                  = review.customer
                %p{ class: 'purchased-car' }
                  = review.car
          .image
            .inner{ style: "background-image: url(#{review.photo.url(:medium)});" }
    %li
      - @reviews[3...6].each do |review|
        .customer-review
          .quote-meta
            .quote
              .inner
                %p
                  = truncate_review review
            .quotee
              .inner
                %p{ class: 'name' }
                  = review.customer
                %p{ class: 'purchased-car' }
                  = review.car
          .image
            .inner{ style: "background-image: url(#{review.photo.url(:medium)});" }
  %ul.small-block-grid-1.medium-block-grid-2.show-for-medium-down
    - @reviews[0...4].each do |review|
      %li
        .customer-review
          .quote-meta
            .quote
              .inner
                %p
                  = truncate_review review
            .quotee
              .inner
                %p{ class: 'name' }
                  = review.customer
                %p{ class: 'purchased-car' }
                  = review.car
          .image
            .inner{ style: "background-image: url(#{review.photo.url(:medium)});" }
%section#show-brands
  .row
    = image_tag 'https://s3-us-west-2.amazonaws.com/mvp-used-cars/images/home/show-brands/car.svg', onerror: "this.onerror=null; this.src='https://s3-us-west-2.amazonaws.com/mvp-used-cars/images//home/show-brands/car.png'"
    %p
      Shop cars from all majors brands
    %p
      Toyota, Nissan, Mitsubishi, Subaru, and more...
    = link_to inventory_path do
      .button View our Inventory

app/views/pages/location.html.haml
= content_for :title do
  Our Location - Misawa Air Force Base
%div#hero
  %header
    .row
      .small-6.small-centered.columns
        = image_tag 'https://s3-us-west-2.amazonaws.com/mvp-used-cars/images/location/header/location.svg', onerror: "this.onerror=null; this.src='https://s3-us-west-2.amazonaws.com/mvp-used-cars/images/location/header/location.png'"
      %h1
        Our Location
      %p
        We'd love to talk and meet with you in person. Come down and say Hi!
%section#directions
  .row
    .small-12.medium-7.large-7.columns#directions-details
      %h2
        Misawa Air Force Base
      %p.hours
        Monday - Saturday:
        %span
          0900 - 1830
        Sunday:
        %span
          By appointment
      %div
        %p
          First stop light outside
          %br
          the POL/Falcon gate take a right
        %address
          Misawa Oka-Misawa 6 chou-me 15-15
          %br
          青森県三沢市岡三沢六丁目１５−１５
        %small
          %a{ href: '#google-maps' }
            View in Google Maps
      %p
        %span{ itemprop: 'telephone' }
          %a{ href: 'tel:080-4058-5771' }
            080-4058-5771
        %span
          or
        %span{ itemprop: 'telephone' }
          %a{ href: 'tel:0176-58-6903' }
            0176-58-6903
    .small-12.medium-5.large-5.columns
      = image_tag 'https://s3-us-west-2.amazonaws.com/mvp-used-cars/images/location/location/map.jpg'
#google-maps.flex-video{ style: 'height: 700px; padding-bottom: 0; margin-bottom: 0;' }
  <iframe style="height: 700px; margin: 0 auto;"width="1500" height="0" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.co.jp/maps?ie=UTF8&amp;q=MVP+Used+Cars&amp;fb=1&amp;gl=jp&amp;hq=mvp+used+cars&amp;hnear=0x5f9c9e15d6a6af33:0x47ad9465cf39c203,Misawa,+Aomori+Prefecture&amp;cid=8853326298653188672&amp;t=m&amp;brcurrent=3,0x5f9b5e39a6e2bd5f:0x3970eedef2c0c878,0&amp;ll=40.696909,141.377349&amp;spn=0.005694,0.020599&amp;z=16&amp;iwloc=A&amp;output=embed"></iframe><br /><small><a href="https://maps.google.co.jp/maps?ie=UTF8&amp;q=MVP+Used+Cars&amp;fb=1&amp;gl=jp&amp;hq=mvp+used+cars&amp;hnear=0x5f9c9e15d6a6af33:0x47ad9465cf39c203,Misawa,+Aomori+Prefecture&amp;cid=8853326298653188672&amp;t=m&amp;brcurrent=3,0x5f9b5e39a6e2bd5f:0x3970eedef2c0c878,0&amp;ll=40.696909,141.377349&amp;spn=0.005694,0.020599&amp;z=16&amp;iwloc=A&amp;source=embed" style="color:#0000FF;text-align:center;">View Larger Map</a></small>