config/routes.rb
Mvp::Application.routes.draw do
  root 'pages#index'

  post 'contact', to: 'contact#create', as: 'contact_create'

  controller :pages do
    get 'faq', to: 'pages#faq'
    get 'location', to: 'pages#location'
    get 'contact-us', to: 'pages#contact', as: 'contact'
    get 'about-us', to: 'pages#about', as: 'about'
  end

  get '/inventory', to: 'cars#inventory'
  resources :cars

  resources :uploads

  match '/dashboard', to: 'users#dashboard', via: 'get'
  resources :users

  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  resources :sessions, only: [:new, :create, :destroy]

  resources :reviews
end

app/models/car.rb
class Car < ActiveRecord::Base
  has_many :uploads, dependent: :destroy

  scope :next, ->(id) { where('id > ?', id).order('id ASC') }
  scope :previous, ->(id) { where('id < ?', id).order('id DESC') }
  scope :without_car_shuffle, lambda { |car, limit| Car.where.not(id: car.id)
                                                       .limit(limit)
                                                       .order('RANDOM()')
                              }

  validates :make, :model, :year, :seats, :transmission,
            :drive, :interior, :exterior, presence: true
  validates :uploads, presence: { message: 'You must upload at least one image' }

  accepts_nested_attributes_for :uploads, allow_destroy:  true

  def previous
    Car.previous(self.id).first
  end

  def next
    Car.next(self.id).first
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :signed_in_user, except: [:show, :inventory]
  before_action :admin_user, except: [:show, :inventory]
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  before_action :set_message, only: [:inventory, :show, :create]
  layout 'user', only: [:index, :new, :edit, :create]

  def inventory
    @cars = Car.all(order: 'created_at DESC')
    @body_id = 'inventory'
  end

  def index
    @cars = Car.paginate(page: params[:page])
    @mainid = 'car-index'
  end

  def show
    @cars = Car.without_car_shuffle(@car, 3)
    @previous = @car.previous
    @next = @car.next
    @uploads = @car.uploads
    @body_id = 'car-details'
  end

  def new
    @car = Car.new
    @mainid = 'new-car'
  end

  def edit
    @mainid = 'edit-car'
  end

  def create
    @car = Car.new(car_params)
    @mainid = 'new-car'

    if @car.save
      redirect_to cars_path, notice: 'Car was successfully created'
    else
      render :new
    end
  end

  def update
    if @car.update(car_params)
      redirect_to @car, notice: 'Car was successfully updated'
    else
      redirect_to :edit
    end
  end

  def destroy
    @car.destroy
    @car.uploads.each do |upload|
      upload.destroy
    end
    redirect_to inventory_path
  end

  private

  # find by named routes parameter
  def set_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:make, :model, :year, :seats, :transmission, :drive, :interior, :exterior, uploads_attributes: [:upload, :id, :_destroy])
  end
end

app/helpers/cars_helper.rb
module CarsHelper
  def scale_car_title(make, model)
    class_name = make.length + model.length >= 15 ? 'smaller' : nil

    content_tag(:h1, class: class_name) do
      concat(make + ' ')
      concat(content_tag(:span) { model })
    end
  end
end

app/views/cars/_car.html.haml
%tr
  %td
    = link_to image_tag(car.uploads.first.upload.url(:thumb)), edit_car_path(car)
  %td
    = car.make
  %td
    = car.model
  %td
    = car.transmission
  %td
    = car.drive
  %td
    = car.year
  %td
    = car.seats
  %td
    = car.interior
  %td
    = car.exterior
  %td
    = link_to "delete", car, method: :delete,
    data: {confirm: "Are you sure you want to delete this car"}

app/views/cars/_form.html.haml
.row
  .small-12.columns
    = form_for @car, html: { multipart: true, id: "fileupload", "data-abide" => true } do |f|
      - if @car.errors.any?
        #error_explanation
          %h2
            = pluralize @car.errors.count, "error"
            prohibited this car from being saved:
          %ul
            - @car.errors.full_messages.each do |msg|
              %li
                = msg
      .field
        = f.label :make
        = f.text_field :make, required: true, placeholder: 'Toyota'
        %small.error The make is required
      .field
        = f.label :model
        = f.text_field :model, required: true, placeholder: 'Surf'
        %small.error The model is required
      .field#transmission
        = f.label :transmission
        = f.select :transmission, options_for_select([['A/T','A/T'], ['M/T','M/T']]), required: true
      .field#drive
        = f.label :drive
        = f.select :drive, options_for_select([['4WD','4WD'], ['2WD','2WD']]), required: true
      .field
        = f.label :year
        = f.text_field :year, required: true, placeholder: '2000'
        %small.error The year is required
      .field
        = f.label :seats
        = f.text_field :seats, required: true, placeholder: '2'
        %small.error The number of seats are required
      .field
        = f.label :interior
        = f.text_field :interior, required: true, placeholder: 'Black'
        %small.error The interior color is required
      .field
        = f.label :exterior
        = f.text_field :exterior, required: true, placeholder: 'Black'
        %small.error The exterior color is required
      - if f.object.new_record?
        .row#new-images
          .small-12.columns
            %h4
              Add images
            %p
              You must upload at least one image
            = f.fields_for :uploads_attributes do |upload_fields|
              = button_tag type: 'file', class: 'button', id:'find-file-button' do
                %p Select Car Images
                = upload_fields.file_field :upload, multiple: true, name: "car[uploads_attributes][][upload]", required: true
        = button_tag type: 'submit', class: 'button', id: 'create-car-button' do
          Create Car

      - unless f.object.new_record?
        .row#delete-images
          .small-12.columns
            %h4
              Old images
            %p
              Check the box to delete
            = f.fields_for :uploads do |upload_fields|
              .small-6.medium-3.columns
                = link_to image_tag(upload_fields.object.upload.url(:thumb)), upload_fields.object.upload.url(:original)
                = upload_fields.check_box :_destroy
        .actions
          = button_tag type: 'submit', class: 'button split' do
            = action_name.capitalize
            Car
            %span{ "data-dropdown" => "drop"}
            %ul#drop.f-dropdown{ "data-dropdown-content" => true }
              %li
                = link_to 'Delete this car', @car, method: :delete, data: { confirm: 'Are you sure?' }

app/views/cars/edit.html.haml
%h1
  Edit car:
  %span
    = @car.make
    = @car.model
= render 'form'

app/views/cars/index.html.haml
= content_for :title do
  All cars

.row
  .small-12.columns
    %h1.small-12.medium-3.columns
      All cars
    = link_to 'Add car', new_car_path, class: 'button small-12 medium-2 columns'
.row
  .small-12.columns
    = will_paginate @cars, renderer: FoundationPagination::Rails
    %table
      %thead
        %tr
          %th Image
          %th Make
          %th Model
          %th Transmission
          %th Drive
          %th Year
          %th Seats
          %th Interior
          %th Exterior
          - if current_user.admin?
            %th Delete
      %tbody
        = render @cars
    = will_paginate @cars, renderer: FoundationPagination::Rails

app/views/cars/inventory.html.haml
= content_for :title do
  Our Inventory - Subaru, Nissan, and More
%div#hero
  %header
    .row
      .small-6.small-centered.columns
        = image_tag 'inventory/header/car.svg', onerror: "this.onerror=null; this.src='/assets/inventory/header/car.png'"
      %h1
        Our Inventory
      %p
        Browse our current selection from the comfort of you computer
%section#cars
  .row
    .small-12.small-centered.columns
      %ul.small-block-grid-1.medium-block-grid-3
        - @cars.each do |car|
          - unless car.uploads.first.nil?
            %li
              %p
                = car.year
                = car.make
                = car.model
              = link_to image_tag(car.uploads.first.upload.url(:medium)), car
%section#request-car
  .row
    %h2
      Can't Find what you're looking for?
    %p
      We can special order specific cars upon request
    = link_to( contact_path(subject: 'Request a car', anchor: 'send-us-a-message') ) do
      .button Make a Request

app/views/cars/new.html.haml
= content_for :title do
  Add a new car

%h1
  Add a new car
= render 'form'

app/views/cars/show.html.haml
%header
  .row
    = scale_car_title(@car.make, @car.model)
%section#car-details
  #gallery
    .row
      .small-12.columns
        %ul.small-block-grid-2.medium-block-grid-3.clearing-thumbs(data-clearing)
          - @uploads.each do |u|
            %li
              = link_to image_tag(u.upload.url(:medium)), u.upload.url

  #info
    .row
      .small-6.medium-3.columns
        %p
          %span
            Make:
          %span
            = @car.make
        %p
          %span
            Model:
          %span
            = @car.model
      .small-6.medium-3.columns
        %p
          %span
            Year:
          %span
            = @car.year
        %p
          %span
            Seats:
          %span
            = @car.seats
      .small-6.medium-3.columns
        %p
          %span
            Transmission:
          %span
            = @car.transmission
        %p
          %span
            Drive:
          %span
            = @car.drive
      .small-6.medium-3.columns
        %p
          %span
            Interior:
          %span
            = @car.interior
        %p
          %span
            Exterior:
          %span
            = @car.exterior
%section#enquire
  = link_to contact_path(subject: "Enquiry: #{@car.year} #{@car.make} #{@car.model}", anchor: 'send-us-a-message'), class: 'button' do
    Enquire
    %br
    %span
      for more details
%section#view-more
  .row
    .small-12.small-centered.columns
      %h1
        View More
      %ul.small-block-grid-1.medium-block-grid-3
        - @cars.each do |car|
          %li
            %p
              = car.year
              = car.make
              = car.model
            - unless car.uploads.blank?
              = link_to image_tag(car.uploads.first.upload.url), car