config/routes.rb
Mvp::Application.routes.draw do
  root 'pages#index'

  post 'contact', to: 'contact#create', as: 'contact_create'

  controller :pages do
    get 'faq', to: 'pages#faq'
    get 'location', to: 'pages#location'
    get 'contact-us', to: 'pages#contact', as: 'contact'
    get 'about-us', to: 'pages#about', as: 'about'
  end

  get '/inventory', to: 'cars#inventory'
  resources :cars

  resources :uploads

  match '/dashboard', to: 'users#dashboard', via: 'get'
  resources :users

  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  resources :sessions, only: [:new, :create, :destroy]

  resources :reviews
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :signed_in_user, expect: [:show]
  before_action :admin_user, expect: [:show]
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  layout 'user', except: [:show]

  def index
    @reviews = Review.paginate(page: params[:page])
    @mainid = 'reviews'
  end

  def new
    @review = Review.new
    @mainid = 'new-review'
  end

  def edit
    @mainid = 'edit-review'
  end

  def create
    @review = Review.new(review_params)
    @mainid = 'new-review'

    if @review.save
      redirect_to reviews_path, notice: 'Review was successfully created'
    else
      render :new
    end
  end

  def destroy
    @review.destroy
    redirect_to reviews_path
  end

  def show
    @message = Message.new
  end

  def update
    if @review.update(review_params)
      redirect_to reviews_path, notice: 'Review was successfully updated'
    else
      redirect_to :edit
    end
  end

  private

  def set_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:customer, :body, :car, :photo)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.haml
.row
  .small-12.columns
    = form_for @review, html: { multipart: true, "data-abide" => true } do |f|
      - if @review.errors.any?
        #error_explanation
          %h2
            = pluralize @review.errors.count, "error"
            prohibited this review from being saved:
          %ul
            - @review.errors.full_messages.each do |msg|
              %li
                = msg
      .field
        = f.label :customer, "Customer's name"
        = f.text_field :customer, required: true, placeholder: 'Billy Jean'
        %small.error The customer's name is required
      .field
        = f.label :car, 'Purchased car'
        = f.text_field :car, required: true, placeholder: 'Nissan Skyline GTR'
        %small.error The customer's car is required
      .field
        = f.label :body, 'Review'
        = f.text_area :body, required: true, placeholder: 'Service was great'
        %small.error The review body is required
      - if f.object.new_record?
        .row#new-image
          .small-12.columns
            %h4
              Add images
            %p
              You must upload one image
            = button_tag type: 'file', class: 'button', id:'find-file-button' do
              %p Select Customer Image
              = f.file_field :photo, required: true
        = button_tag 'Create Review', type: 'submit', class: 'button', id: 'create-review-button'
      - unless f.object.new_record?
        .row#delete-image
          .small-12.columns
            %h4
              Uploaded image
            .small-12.columns
              = link_to image_tag(@review.photo.url(:medium)), @review.photo.url(:original)
        .actions
          = button_tag type: 'submit', class: 'button split' do
            = action_name.capitalize
            Review
            %span{ "data-dropdown" => "drop"}
            %ul#drop.f-dropdown{ "data-dropdown-content" => true }
              %li
                = link_to 'Delete this review', @review, method: :delete, data: { confirm: 'Are you sure?' }

app/views/reviews/_review.html.haml
%tr
  %td
    = link_to image_tag(review.photo.url(:thumb)), edit_review_path(review)
  %td
    = review.customer
  %td
    = review.body
  %td
    = review.car
  %td
    = link_to "delete", review, method: :delete,
    data: {confirm: "Are you sure you want to delete this review?"}

app/views/reviews/edit.html.haml
%h1
  Edit a review
= render 'form'

app/views/reviews/index.html.haml
= content_for :title do
  All reviews

.row
  .small-12.columns
    %h1.small-12.medium-3.columns
      All reviews
    = link_to 'Add review', new_review_path, class: 'button small-12 medium-2 columns'
.row
  .small-12.columns
    = will_paginate @reviews, renderer: FoundationPagination::Rails
    %table
      %thead
        %tr
          %th Image
          %th Customer
          %th Review
          %th Car
          - if current_user.admin?
            %th Delete
      %tbody
        = render @reviews
    = will_paginate @reviews, renderer: FoundationPagination::Rails

app/views/reviews/new.html.haml
%h1
  Add a review
= render 'form'

app/views/reviews/show.html.haml
.row
  .small-12.medium-3.columns
    = image_tag(@review.photo.url(:medium))
    %h1
      = @review.customer
    %p
      = @review.car

  .small-12.medium-9.columns
    %p
      = @review.body