config/routes.rb
Mvp::Application.routes.draw do
  root 'pages#index'

  post 'contact', to: 'contact#create', as: 'contact_create'

  controller :pages do
    get 'faq', to: 'pages#faq'
    get 'location', to: 'pages#location'
    get 'contact-us', to: 'pages#contact', as: 'contact'
    get 'about-us', to: 'pages#about', as: 'about'
  end

  get '/inventory', to: 'cars#inventory'
  resources :cars

  resources :uploads

  match '/dashboard', to: 'users#dashboard', via: 'get'
  resources :users

  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  resources :sessions, only: [:new, :create, :destroy]

  resources :reviews
end

app/views/layouts/_flash.html.haml
-# https://gist.github.com/lengarvey/5352323
- flashes = {:notice => 'success', :alert => 'standard', :error => 'alert', :secondary => 'secondary'}
- flashes.each do |key, value|
  - if flash[key]
    .alert-box{:class => value, :data => { :alert => '' } }
      = flash[key]
      = link_to '&times;'.html_safe, '#', :class => 'close'

app/views/layouts/_footer.html.haml
%footer
  .row
    = form_for @message, url: contact_create_path, html: {  class: 'large-4 columns', data: { abide: true } } do |f|
      .row
        %h7
          Contact Us
        .sweet-honey
          = f.label :sweet_honey, "This is a honeypot, if you see this you're CSS is turned off or you're a bot. If you're not a bot don't fill it in."
          = f.text_field :sweet_honey
        .small-12.columns
          = f.label :name
          %span.user-icon
          = f.text_field( :name, placeholder: 'Name*', 'required pattern' => '[a-zA-Z]' )
          %small.error
            Name is required
        .small-12.columns
          = f.label :email
          %span.email-icon
          = f.email_field( :email, placeholder: 'Email Address*', pattern: 'email', required: true )
          %small.error
            Please enter a valid email
        .small-12.columns
          = f.label :phone
          %span.phone-icon
          = f.telephone_field( :phone, placeholder: 'Phone number' )
        #form-message.small-12.columns
          = f.label :body
          %span.message-icon
          = f.text_area( :body, placeholder: 'Message*' )
        .small-12.columns
          = f.submit( 'Send', class: 'button small small-12 columns' )

    .large-4.columns
      %h7
        About Us
      %p
        MVP Used Cars has been delivering quality cars to the men and women of Misawa Air Force Base for 10+ years.
    .large-4.columns
      %h7
        More Links
      %ul#more-links
        %li
          %a{ href: root_path } Home
        %li
          %a{ href: inventory_path } Inventory
        %li
          %a{ href: faq_path } FAQ
        %li
          %a{ href: about_path } About Us
        %li
          %a{ href: location_path } Location
        %li
          %a{ href: contact_path } Contact Us
        - if false
          %li
            %a{ href: '#' } Our Blog
          %li
            %a{ href: '#' } Terms of Use
  .row
    #social.large-4.large-push-8.columns.show-for-large-up
      %ul.inline-list.right
        %li
          %a.facebook{ href: 'https://facebook.com/mvpusedcars' }
        %li
          %a.twitter{ href: 'https://twitter.com/mvpusedcars' }
        %li
          %a.gplus{ href: 'https://plus.google.com/114770703043987053078/about' }
        %li
          %a.pinterest{ href: 'http://www.pinterest.com/mvpusedcars/' }
    #social.small-4.columns.show-for-medium-down.small-centered.hide-for-large-up
      %ul.inline-list
        %li
          %a.facebook{ href: 'https://facebook.com/mvpusedcars' }
        %li
          %a.twitter{ href: 'https://twitter.com/mvpusedcars' }
        %li
          %a.gplus{ href: 'https://plus.google.com/114770703043987053078/about' }
        %li
          %a.pinterest{ href: 'http://www.pinterest.com/mvpusedcars/' }
    %small.copyright
      = "© MVP Used Cars #{Time.now.year}. All rights reserved."

app/views/layouts/_nav_car_details.html.haml
.fixed
  %nav#car-nav.top-bar(data-topbar)
    .nav-logo
      = link_to image_tag('simple-logo.png'), root_path
    %ul.title-area
      %li.name
        = link_to 'Inventory', inventory_path
    %section.top-bar-section
      %ul.right
        %li.divider
        %li
          = link_to(@previous) do
            %span.prev-main
            Prev
        %li.divider
        %li
          = link_to(@next) do
            Next
            %span.next-main

    %section#nav-prev-next.show-for-small-only
      %ul.right
        - unless @previous.blank?
          %li.prev-small
            = link_to '', @previous
        - unless @next.blank?
          %li.next-small
            = link_to '', @next

app/views/layouts/_nav_main.html.haml
%nav#main-nav.top-bar(data-topbar)
  %ul.title-area
    %li.name
      %a{ href: '/' }
        = image_tag("https://s3-us-west-2.amazonaws.com/mvp-used-cars/images/simple-logo.png", alt: "Home")
    %li.toggle-topbar.menu-icon
      %a{ href: "#" }
        %span
          menu
  %section.top-bar-section
    %ul.right
      = nav_link 'Home', root_path
      = nav_link 'Inventory', inventory_path
      = nav_link 'FAQ', faq_path
      = nav_link 'About Us', '/about-us'
      = nav_link 'Location', location_path
      = nav_link 'Contact Us', '/contact-us'

app/views/layouts/_nav_user.html.haml
.fixed.show-for-large-up
  %nav.top-bar.show-for-large-up(data-topbar)
    %ul.title-area
      %li.name
        .nav-logo
          = link_to image_tag('simple-logo.png'), dashboard_path
      %li.toggle-topbar.menu-icon
        = link_to 'Menu', '#'

    %section.top-bar-section
      %ul.right
        %li.divider
        %li.has-dropdown
          = link_to @current_user.name, '#', id: 'username'
          %ul.dropdown
            %li
              = link_to 'Settings', edit_user_path(@current_user)
            %li
              = link_to 'Sign out', signout_path, method: :delete

%nav.tab-bar.hide-for-large-up
  %section.left-small
    %a.left-off-canvas-toggle.menu-icon{ href: '#' }
      %span
  %section.middle.tab-bar-section
    .nav-logo
      = link_to image_tag('simple-logo.png'), dashboard_path

app/views/layouts/_sidebar.html.haml
#sidebar.sidebar.show-for-large-up
  .sidebar-inner
    %ul.side-nav
      = sidebar_active_link_to(dashboard_path) do
        %span.dashboard.icon
        Dashboard
      - if current_user.admin?
        = sidebar_active_link_to(cars_path) do
          %span.cars.icon
          Cars
        = sidebar_active_link_to(users_path) do
          %span.users.icon
          Users
        = sidebar_active_link_to(reviews_path) do
          %span.reviews.icon
          Reviews

%aside.left-off-canvas-menu
  %ul.off-canvas-list
    %li
      = link_to 'Dashboard', dashboard_path
    - if current_user.admin?
      %li
        = link_to 'Cars', cars_path
      %li
        = link_to 'Users', users_path
      %li
        = link_to 'Reviews', reviews_path
      %li
        %label
          = current_user.name
      %li
        = link_to 'Settings', edit_user_path(@current_user)
      %li
        = link_to 'Sign out', signout_path, method: :delete

app/views/layouts/application.html.haml
!!! 5

/[if lt IE 7]
  %html.no-js.lt-ie9.lt-ie8.lt-ie7{ lang: 'en' }
/[if IE 7]
  %html.no-js.lt-ie9.lt-ie8{ lang: 'en' }
/[if IE 8]
  %html.no-js.lt-ie9{ lang: 'en' }
/[if gt IE 8]
%html.no-js{:lang => "en"}
  / <![endif]
  %head
    %meta{:charset => "utf-8"}/
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
    %title
      = content_for?(:title) ? yield(:title) + " | MVP Used Cars" : "MVP Used Cars"
    = stylesheet_link_tag "application", "http://fonts.googleapis.com/css?family=Lato:300,400,700"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
<<<<<<< HEAD
    -# - if Rails.env.production?
      -# = render 'layouts/google_analytics'
=======
>>>>>>> parent of eca6446... Add google analytics

  %body{ id: "#{ body_id }" }
    -# render navigation based on if within one of the `pages` pages
    - unless controller_name  == 'cars' && action_name == 'show'
      = render 'layouts/nav_main'
    - else
      = render 'layouts/nav_car_details'
    %main
      = render 'layouts/flash'
      = yield
      - unless controller_name == 'sessions'
        = render 'layouts/footer'
    = javascript_include_tag "application"

app/views/layouts/user.html.haml
!!! 5

/[if lt IE 7]
  %html.no-js.lt-ie9.lt-ie8.lt-ie7{ lang: 'en' }
/[if IE 7]
  %html.no-js.lt-ie9.lt-ie8{ lang: 'en' }
/[if IE 8]
  %html.no-js.lt-ie9{ lang: 'en' }
/[if gt IE 8]
%html.no-js{:lang => "en"}
  / <![endif]
  %head
    %meta{:charset => "utf-8"}/
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
    %title
      = content_for?(:title) ? yield(:title) + " | MVP Used Cars" : "MVP Used Cars"
    = stylesheet_link_tag "application", "http://fonts.googleapis.com/css?family=Lato:300,400,700"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags

  %body#user-layout
    %main
      .off-canvas-wrap
        .inner-wrap
          = render 'layouts/nav_user'
          .content
            = render 'layouts/sidebar'
            .mainbar{ id: "#{@mainid}" }
              = render 'layouts/flash'
              = yield
    = javascript_include_tag "application"